version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    command: ruby main.rb
    depends_on:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:4.0.1-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - ./redis:/data
